# Generated by Django 4.2.3 on 2023-07-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
    ]
