# Generated by Django 4.2.3 on 2023-07-07 12:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0005_farmer_delete_farmerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'All farmers data',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='farmer',
        ),
    ]
