# Generated by Django 4.2.3 on 2023-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_farmer_delete_farmerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
