# Generated by Django 4.2.3 on 2023-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_farmer_mobile_farmer_pincode_farmer_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
