# Generated by Django 4.2.3 on 2023-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_farmer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='otp_chance',
        ),
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='contry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='static/home/pimages'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
