# Generated by Django 4.2.3 on 2023-07-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_shared_equipment_equipment_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_contact',
            new_name='no_of_eq',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='equipment_id',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='shared_equipment',
            name='euipment_pincode',
        ),
        migrations.RemoveField(
            model_name='shared_equipment',
            name='no_of_equipment',
        ),
    ]
