# Generated by Django 4.2.3 on 2023-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_equipment_company_shared_equipment_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_equipment',
            name='image',
            field=models.ImageField(upload_to='static/home/eqimages'),
        ),
    ]
