# Generated by Django 4.2.3 on 2023-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shared_equipment_city_shared_equipment_contry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_equipment',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
