# Generated by Django 4.2.3 on 2023-07-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shared_equipment_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared_equipment',
            old_name='contry',
            new_name='country',
        ),
    ]
