# Generated by Django 4.2.3 on 2023-07-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_contry_shared_equipment_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_equipment',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
